ALLOWED_CATEGORIES = (
    "bag",
    "car parts",
    "clothing",
    "electronics",
    "laptop",
    "perfume",
    "phone",
    "shoes",
    "other",
)


CATEGORY_ALIASES = {
    "bag": "bag",
    "bags": "bag",
    "backpack": "bag",
    "backpacks": "bag",
    "handbag": "bag",
    "purse": "bag",
    "purses": "bag",
    "car part": "car parts",
    "car parts": "car parts",
    "automotive": "car parts",
    "auto accessory": "car parts",
    "clothes": "clothing",
    "clothing": "clothing",
    "apparel": "clothing",
    "fashion": "clothing",
    "electronics": "electronics",
    "electronic": "electronics",
    "audio": "electronics",
    "accessory": "electronics",
    "accessories": "electronics",
    "laptop": "laptop",
    "laptops": "laptop",
    "tablet": "laptop",
    "tablets": "laptop",
    "computer": "laptop",
    "computers": "laptop",
    "perfume": "perfume",
    "cologne": "perfume",
    "fragrance": "perfume",
    "phone": "phone",
    "phones": "phone",
    "cell phone": "phone",
    "cell phones": "phone",
    "mobile phone": "phone",
    "smartphone": "phone",
    "smartphones": "phone",
    "shoe": "shoes",
    "shoes": "shoes",
    "sneaker": "shoes",
    "sneakers": "shoes",
    "boot": "shoes",
    "boots": "shoes",
    "sandals": "shoes",
    "other": "other",
}


RULE_KEYWORDS = (
    ("phone", ("iphone", "smartphone", "cell phone", "mobile phone", "android phone")),
    ("laptop", ("macbook", "laptop", "notebook", "tablet", "ipad")),
    ("perfume", ("perfume", "cologne", "eau de parfum", "fragrance", "body mist")),
    ("shoes", ("shoe", "sneaker", "boot", "sandal", "loafer", "heel")),
    ("car parts", ("bumper", "mirror cap", "brake", "rotor", "headlight", "car part")),
    ("bag", ("backpack", "handbag", "crossbody", "duffel", "purse", "tote bag")),
    (
        "electronics",
        (
            "headphones",
            "earbuds",
            "speaker",
            "charger",
            "monitor",
            "gaming mouse",
            "playstation",
            "play station",
            "ps5",
            "ps 5",
            "xbox",
            "nintendo switch",
            "gaming console",
            "console",
        ),
    ),
    ("clothing", ("shirt", "dress", "hoodie", "jacket", "jeans", "leggings", "t-shirt")),
)


WEIGHT_HINTS_LBS = (
    (("headset", "gaming headset", "headphones", "earbuds"), 1.5),
    (("controller", "gamepad", "joystick"), 1.5),
    (("charger", "charging dock", "charging station", "cable"), 1.0),
    (("playstation", "play station", "ps5", "ps 5"), 8.0),
    (("xbox series x", "xbox series s", "xbox"), 8.0),
    (("nintendo switch", "steam deck", "gaming console"), 4.5),
    (("laptop", "macbook"), 4.0),
    (("monitor",), 9.0),
    (("phone", "iphone", "smartphone"), 1.0),
    (("perfume", "cologne", "fragrance"), 2.0),
    (("shoe", "sneaker", "boot", "sandals"), 3.0),
)
